// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyxpkcujuwlehafcnobw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5eHBrY3VqdXdsZWhhZmNub2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzE4NjcsImV4cCI6MjA2NTcwNzg2N30.vSoexmRXrT9fReTNefOKip0pQDLr1uwnsFmyHJMdU0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);